[tool.poetry]
name = "skellycam"
version = "2023.09.1086"
description = "\"A simple python API for efficiently connecting to and recording synchronized videos from one or multiple cameras 💀📸\""
authors = ["Skelly FreeMoCap <info@freemocap.org>"]
license = "AGPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = ">3.10, <3.12"
numpy = "1.24.4"
opencv-contrib-python = "4.8.*"
pydantic = "<2"
PyQt6 = "6.5.2"
matplotlib = "3.7.2"
pandas = "2.1.0"
pillow = "^10.0.1"
setproctitle = "^1.3.3"
tqdm = "^4.66.1"
pyqtgraph = "^0.13.3"
qtpy = "^2.4.0"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
pre-commit = "^3.4.0"
pyinstaller = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
